spring.application.name=FindMyDoctor-Webservice

server.port=9091

logging.level.org.springframework.security=DEBUG

# ===============================
# Database Configuration
# ===============================
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/doctors?createDatabaseIfNotExist=true
spring.datasource.password=Sanjana@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA & Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# ===============================
# Gmail SMTP Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
#some live servers block 587 port
#spring.mail.port=587 
spring.mail.username=sanjanakatal04@gmail.com
spring.mail.password=yhfa jxiu znjx lkki

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

